---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-api-credentials
  namespace: musicloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secretstore
    kind: ClusterSecretStore
  target:
    name: google-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: prod/Musicloud/GoogleApi
        property: apiKey
