---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: playback-server-secret
  namespace: radioterio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secretstore
    kind: ClusterSecretStore
  target:
    name: playback-server-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: prod/Radioterio/PlaybackServer
        property: JWT_SECRET
