---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: mysql-backup-cronjob
  namespace: davinciapps
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 0
  schedule: "30 45 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: alpine:3.18
              env:
              - name: MYSQL_HOST
                value: internal-mysql.davinciapps.svc.cluster.local
              - name: MYSQL_DB
                value: macracoon
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: mysql-credentials
                    key: user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-credentials
                    key: password
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-credentials
                    key: token
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e  # Exit immediately if a command fails

                  apk add git mysql-client mariadb-connector-c-dev
                  git config --global user.email "hello@pyldin601.dev"
                  git config --global user.name "Backup Bot"
                  git clone https://pyldin601:"$GITHUB_TOKEN"@github.com/macracoon/database-backups.git
                  
                  mkdir -p database-backups/database/macracoon
                  cd database-backups/database/macracoon
                  mysqldump --no-create-info --no-tablespaces --skip-dump-date -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB > macracoon_backup.sql
                  
                  git add macracoon_backup.sql
                  
                  # Check if there are any changes
                  git diff --cached --exit-code && echo "No changes to commit." && exit 0
                  
                  git commit -m "Macracoon Database Backup"
                  git push
                  exit 0
          restartPolicy: OnFailure
