---
apiVersion: v1
kind: Namespace
metadata:
  name: davinciapps
  labels:
    name: davinciapps
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-web
  namespace: davinciapps
  labels:
    kubernetes.io/service-name: external-web
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.240
    conditions: {}
ports:
  - name: http
    port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: external-web
  namespace: davinciapps
spec:
  selector: {}
  ports:
    - name: http
      port: 8081
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-mysql
  namespace: davinciapps
  labels:
    kubernetes.io/service-name: external-web
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.0.240
    conditions: {}
ports:
  - name: mysql
    port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: internal-mysql
  namespace: davinciapps
spec:
  selector: {}
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: external-web
  namespace: davinciapps
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`davinciapps.com`) || Host(`www.davinciapps.com`)
      services:
        - kind: Service
          name: external-web
          port: 8081
  tls:
    certResolver: default
