---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`coins1.homefs.biz`)
      services:
        - kind: Service
          name: app
          port: 8080
          scheme: http
  tls:
    certResolver: default
---
kind: Service
apiVersion: v1
metadata:
  name: app
spec:
  selector:
    deployment: app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: app
  template:
    metadata:
      labels:
        deployment: app
    spec:
      containers:
        - name: app
          image: pldin601/superorder-v1:da2f61e8cff624f03586b0ab072690866a329566
          env:
            - name: AMQP_URL
              value: amqp://rabbitmq?heartbeat=30
            - name: REDIS_HOST
              value: redis
            - name: DB_HOST
              value: postgres
            - name: DB_DATABASE
              value: so
            - name: DB_USER
              value: so
            - name: DB_PASSWORD
              value: so
            - name: SITE_URL
              value: https://coins1.homefs.biz
            - name: CONFIGURATION_PROFILE
              value: development
            - name: COINBASE_API_KEY
              value: ""
            - name: COINBASE_SHARED_SECRET
              value: ""
            - name: STRIPE_SECRET_KEY
              value: ""
            - name: STRIPE_WEBHOOK_SECRET_KEY
              value: ""
            - name: STRIPE_PUBLIC_KEY
              value: ""
            - name: SIGNUP_DISABLED
              value: "1"
            - name: TG_IPN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app
                  key: TG_IPN_SECRET
            - name: MIXPANEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: MIXPANEL_TOKEN
            - name: RUNNER_LOGENTRIES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: RUNNER_LOGENTRIES_TOKEN
            - name: LOGGER_LOGENTRIES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: LOGGER_LOGENTRIES_TOKEN
            - name: APICALL_LOGENTRIES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: APICALL_LOGENTRIES_TOKEN
            - name: PAYMENTS_LOGENTRIES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: PAYMENTS_LOGENTRIES_TOKEN
            - name: COINPAYMENTS_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: app
                  key: COINPAYMENTS_PUBLIC_KEY
            - name: COINPAYMENTS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app
                  key: COINPAYMENTS_SECRET_KEY
            - name: COINPAYMENTS_IPN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app
                  key: COINPAYMENTS_IPN_SECRET
