apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3p
  namespace: 3p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3p
  template:
    metadata:
      labels:
        app: 3p
    spec:
      containers:
        - name: 3p
          image: pldin601/3p:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: 3p
  namespace: 3p
spec:
  type: ClusterIP
  selector:
    app: 3p
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: 3p
  namespace: 3p
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`3p.pyldin601.xyz`)
      services:
        - kind: Service
          name: 3p
          port: http
          scheme: http
  tls:
    certResolver: default
