apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppp
  namespace: ppp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppp
  template:
    metadata:
      labels:
        app: ppp
    spec:
      containers:
        - name: ppp
          image: pldin601/3p:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ppp
  namespace: ppp
spec:
  type: ClusterIP
  selector:
    app: ppp
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ppp
  namespace: ppp
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ppp.pyldin601.xyz`)
      services:
        - kind: Service
          name: ppp
          port: http
          scheme: http
  tls:
    certResolver: default
