---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polyglot-bot-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: polyglot-bot-server
  template:
    metadata:
      labels:
        deployment: polyglot-bot-server
    spec:
      containers:
        - name: polyglot-bot-server
          image: pldin601/polyglot-bot@sha256:4052c4a5a66004c8185ca4a6d7d62679316fe32d30662bf0c9acae95f0180317
          env:
            - name: TS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TS_API_KEY
            - name: TG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: polyglot-bot-secret
                  key: TG_BOT_TOKEN
