---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homefs-hub-telegram-bot-secret
  namespace: homefs-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secretstore
    kind: ClusterSecretStore
  target:
    name: homefs-hub-telegram-bot-secret
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: prod/homefs/global
        property: HOMEFS_HUB_TELEGRAM_BOT_TOKEN
