---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homefs-hub-telegram-bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: homefs-hub-telegram-bot
  template:
    metadata:
      labels:
        deployment: homefs-hub-telegram-bot
    spec:
      containers:
        - name: homefs-hub-telegram-bot
          image: ghcr.io/pyldin601/homefs-telegram-bot:f14473d40db215332096c0965a22cb3bbb72602c
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama.default.svc.cluster.local:11434
            - name: OLLAMA_MODEL
              value: qwen2.5
            - name: ALLOWED_CHAT_IDS
              value: "384980395"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homefs-hub-telegram-bot-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: TOOL_SERVER_URL
              value: http://homefs-hub-tool-server.homefs-hub.svc.cluster.local:8000
