---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homefs-hub-tool-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      deployment: homefs-hub-tool-server
  template:
    metadata:
      labels:
        deployment: homefs-hub-tool-server
    spec:
      containers:
        - name: homefs-hub-tool-server
          image: ghcr.io/pyldin601/homefs-tool-server:2386bd4601c301f9bf3e52b9f2dcd13b9327fb6f
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: TOLOKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: homefs-hub-telegram-bot-secret
                  key: TOLOKA_USERNAME
            - name: TOLOKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homefs-hub-telegram-bot-secret
                  key: TOLOKA_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: homefs-hub-tool-server
spec:
  selector:
    deployment: homefs-hub-tool-server
  ports:
    - name: http
      port: 8000
      targetPort: http
