apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

labels:
  - pairs:
      app: homefs-hub
    includeSelectors: true

resources:
  - namespace.yaml
  - homefs-hub-telegram-bot.yaml
  - externalsecret.yaml
