---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: mysql-backup-cronjob
  namespace: myownradio
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 0
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-backup
              image: alpine:3.18
              env:
              - name: MYSQL_HOST
                value: myownradio-mysql.myownradio.svc.cluster.local
              - name: MYSQL_DB
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: database
              - name: MYSQL_USER
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: username
              - name: MYSQL_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: myownradio-mysql-configmap
                    key: password
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-token
                    key: token
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e  # Exit immediately if a command fails
                  
                  apk add git mysql-client mariadb-connector-c-dev
                  git config --global user.email "hello@pyldin601.dev"
                  git config --global user.name "Backup Bot"
                  git clone https://pyldin601:"$GITHUB_TOKEN"@github.com/pyldin601/servers-backups.git

                  mkdir -p servers-backups/database/myownradio
                  cd servers-backups/database/myownradio
                  mysqldump --no-create-info --no-tablespaces --skip-dump-date -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB > myownradio_backup.sql

                  git add myownradio_backup.sql

                  # Check if there are any changes
                  git diff --cached --exit-code && echo "No changes to commit." && exit 0

                  git commit -m "Myownradio Database Backup"
                  git push
                  exit 0
          restartPolicy: OnFailure
