---
apiVersion: v1
kind: Service
metadata:
  name: shared-redis
spec:
  selector:
    deployment: shared-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: shared-redis
  template:
    metadata:
      labels:
        deployment: shared-redis
    spec:
      volumes:
        - name: shared-redis-data
          persistentVolumeClaim:
            claimName: shared-redis-data
      containers:
        - name: redis
          image: redis:alpine3.18
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          volumeMounts:
            - mountPath: "/data"
              name: shared-redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
